name: nf-core-rnaseq-3.4

channels:
  - conda-forge
  - bioconda
  - mvdbeek
  - defaults

dependencies:
  - bioconda::bedtools=2.30.0
  - conda-forge::coreutils=8.30
  - bioconda::fastqc=0.11.9
  - bioconda::samtools=1.12
  - bioconda::picard=2.25.7
  - bioconda::preseq=3.1.2
  - bioconda::qualimap=2.2.2d
  - bioconda::rsem=1.3.1
  - bioconda::star=2.7.6a
  - bioconda::rseqc=3.0.1
  - bioconda::bbmap=38.93
  - bioconda::hisat2=2.2.1
  - bioconda::salmon=1.4.0
  - bioconda::stringtie=2.1.7
  - bioconda::subread=2.0.1
  - bioconda::cutadapt=3.4
  - bioconda::trim-galore=0.6.7
  - bioconda::sortmerna=4.3.3
  - bioconda::stringtie=2.1.7
  - bioconda::umi_tools=1.1.1
  - bioconda::ucsc-twobitinfo=377
